#项目名端口配置
server:
  servlet:
    context-path: /
  port: 8081

#thymeleaf配置
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html

#数据库配置
  profiles:
    active: a
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=UTF-8
      username: root
      password: root

#jpa配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true

#配置上传文件大小限制
  servlet:
    multipart:
      max-request-size: 100Mb
      max-file-size: 100Mb
      location: D:\test

  mail:
    host: smtp.163.com
    username: 13886620497@163.com
    password: wsxzaq1@
    port: 25
    protocol: smtp
    default-encoding: UTF-8

  # redis:
    # database: 0
    #  host: 127.0.0.1
    # port: 6379
    # password: root
    #  jedis:
    #   pool:
    #   max-active: 8
    #    max-idle: 8
    #    min-idle: 0